[package]
edition = "2018"
name = "rjobs-macros"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = {version = "1.0", features = ["full"]}

[dev-dependencies]
anyhow = "^1.0"
